// Generated by CoffeeScript 1.10.0
(function() {
  var apiRouters, app, bodyParser, cors, express, logger, path, taskRouters, userRouters;

  express = require('express');

  path = require('path');

  logger = require('morgan');

  bodyParser = require('body-parser');

  cors = require('cors');

  apiRouters = require('./../routes/api');

  userRouters = require('./../routes/user');

  taskRouters = require('./../routes/task');

  app = express();

  app.use(logger('dev'));

  app.use(bodyParser.json());

  app.use(bodyParser.urlencoded({
    extended: false
  }));

  app.use(cors());

  app.use('/api', apiRouters);

  app.use('/api', userRouters);

  app.use('/api', taskRouters);

  app.use(function(req, res, next) {
    var err;
    err = new Error('Not Found');
    err.status = 404;
    return next(err);
  });

  app.use(function(err, req, res, next) {
    return res.send(err.status || 500, {
      message: err.message,
      error: err
    });
  });

  module.exports = app;

}).call(this);

//# sourceMappingURL=app.js.map
